"""Initial schema

Revision ID: 4d38bd95ed11
Revises: 
Create Date: 2026-03-25 23:29:02.722432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d38bd95ed11'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('closed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_trade_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_trade_events_external_id'), 'raw_trade_events', ['external_id'], unique=True)
    op.create_table('trader_classifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trader_classifications_address'), 'trader_classifications', ['address'], unique=False)
    op.create_table('trader_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('total_trades', sa.Integer(), nullable=False),
    sa.Column('win_rate', sa.Float(), nullable=False),
    sa.Column('profit_loss', sa.Float(), nullable=False),
    sa.Column('avg_clv', sa.Float(), nullable=False),
    sa.Column('median_clv', sa.Float(), nullable=False),
    sa.Column('directional_purity', sa.Float(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trader_profiles_address'), 'trader_profiles', ['address'], unique=False)
    op.create_table('trader_wallets',
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('owner_address', sa.String(), nullable=True),
    sa.Column('ens_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('address')
    )
    op.create_index(op.f('ix_trader_wallets_owner_address'), 'trader_wallets', ['owner_address'], unique=False)
    op.create_table('markets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('closed', sa.Boolean(), nullable=False),
    sa.Column('resolution_source', sa.String(), nullable=True),
    sa.Column('end_date_iso', sa.DateTime(), nullable=True),
    sa.Column('market_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('trader_score_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('repricing_score', sa.Float(), nullable=False),
    sa.Column('resolution_score', sa.Float(), nullable=False),
    sa.Column('composite_score', sa.Float(), nullable=False),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['address'], ['trader_wallets.address'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trader_score_snapshots_topic'), 'trader_score_snapshots', ['topic'], unique=False)
    op.create_table('market_tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('market_id', sa.String(), nullable=False),
    sa.Column('tag', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_tags_tag'), 'market_tags', ['tag'], unique=False)
    op.create_table('outcomes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('market_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('asset_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('closed_positions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trader_address', sa.String(), nullable=False),
    sa.Column('market_id', sa.String(), nullable=False),
    sa.Column('outcome_id', sa.Integer(), nullable=False),
    sa.Column('buy_size', sa.Float(), nullable=False),
    sa.Column('buy_avg_price', sa.Float(), nullable=False),
    sa.Column('sell_size', sa.Float(), nullable=False),
    sa.Column('sell_avg_price', sa.Float(), nullable=False),
    sa.Column('realized_pnl', sa.Float(), nullable=False),
    sa.Column('realized_edge', sa.Float(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.ForeignKeyConstraint(['outcome_id'], ['outcomes.id'], ),
    sa.ForeignKeyConstraint(['trader_address'], ['trader_wallets.address'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market_signal_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('market_id', sa.String(), nullable=False),
    sa.Column('outcome_id', sa.Integer(), nullable=False),
    sa.Column('signal_type', sa.String(), nullable=False),
    sa.Column('signal_strength', sa.Float(), nullable=False),
    sa.Column('directional_bias', sa.String(), nullable=False),
    sa.Column('explanation', sa.JSON(), nullable=False),
    sa.Column('top_traders', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.ForeignKeyConstraint(['outcome_id'], ['outcomes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('position_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trader_address', sa.String(), nullable=False),
    sa.Column('market_id', sa.String(), nullable=False),
    sa.Column('outcome_id', sa.Integer(), nullable=False),
    sa.Column('current_size', sa.Float(), nullable=False),
    sa.Column('avg_entry_price', sa.Float(), nullable=False),
    sa.Column('unrealized_pnl', sa.Float(), nullable=False),
    sa.Column('snapshot_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.ForeignKeyConstraint(['outcome_id'], ['outcomes.id'], ),
    sa.ForeignKeyConstraint(['trader_address'], ['trader_wallets.address'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('market_id', sa.String(), nullable=False),
    sa.Column('outcome_id', sa.Integer(), nullable=False),
    sa.Column('best_bid', sa.Float(), nullable=False),
    sa.Column('best_ask', sa.Float(), nullable=False),
    sa.Column('mid_price', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.ForeignKeyConstraint(['outcome_id'], ['outcomes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_snapshots_timestamp'), 'price_snapshots', ['timestamp'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('market_id', sa.String(), nullable=False),
    sa.Column('outcome_id', sa.Integer(), nullable=False),
    sa.Column('trader_address', sa.String(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('size', sa.Float(), nullable=False),
    sa.Column('notional', sa.Float(), nullable=False),
    sa.Column('transaction_hash', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('is_reprice', sa.Boolean(), nullable=False),
    sa.Column('clv_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.ForeignKeyConstraint(['outcome_id'], ['outcomes.id'], ),
    sa.ForeignKeyConstraint(['trader_address'], ['trader_wallets.address'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_timestamp'), 'trades', ['timestamp'], unique=False)
    op.create_index(op.f('ix_trades_transaction_hash'), 'trades', ['transaction_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_transaction_hash'), table_name='trades')
    op.drop_index(op.f('ix_trades_timestamp'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_price_snapshots_timestamp'), table_name='price_snapshots')
    op.drop_table('price_snapshots')
    op.drop_table('position_snapshots')
    op.drop_table('market_signal_snapshots')
    op.drop_table('closed_positions')
    op.drop_table('outcomes')
    op.drop_index(op.f('ix_market_tags_tag'), table_name='market_tags')
    op.drop_table('market_tags')
    op.drop_index(op.f('ix_trader_score_snapshots_topic'), table_name='trader_score_snapshots')
    op.drop_table('trader_score_snapshots')
    op.drop_table('markets')
    op.drop_index(op.f('ix_trader_wallets_owner_address'), table_name='trader_wallets')
    op.drop_table('trader_wallets')
    op.drop_index(op.f('ix_trader_profiles_address'), table_name='trader_profiles')
    op.drop_table('trader_profiles')
    op.drop_index(op.f('ix_trader_classifications_address'), table_name='trader_classifications')
    op.drop_table('trader_classifications')
    op.drop_index(op.f('ix_raw_trade_events_external_id'), table_name='raw_trade_events')
    op.drop_table('raw_trade_events')
    op.drop_table('events')
    # ### end Alembic commands ###
